version: "3.7"
services:
  web:
    image: php:7.4-apache
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    volumes:
      - ".:/var/www/html"
    working_dir: /var/www/html
    depends_on:
      - db
    networks:
      - slim_app

  db:
    image: mysql:5.7
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    networks:
      - slim_app

networks:
  slim_app:
    driver: bridge
